### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ergunpp** [mccrodp/gatsby-starter-contentful-i18n#10] opened 2018-11-27 15:08 UTC
I have installed with 
"gatsby new project https://github.com/mccrodp/gatsby-starter-contentful-i18n.git"
 but it runs in to problems:

UNMET PEER DEPENDENCY for:

react@^16.4.2
react-dom@^16.4.2

and warnings:

react-typography@0.15.10 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN gatsby@2.0.55 requires a peer of react@^16.4.2 but none was installed.
npm WARN gatsby@2.0.55 requires a peer of react-dom@^16.4.2 but none was installed.
npm WARN react-intl@2.7.2 requires a peer of react@^0.14.9 || ^15.0.0 || ^16.0.0 but none was installed.
npm WARN gatsby-react-router-scroll@2.0.1 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none was installed.
npm WARN gatsby-react-router-scroll@2.0.1 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0 but none was installed.
npm WARN react-hot-loader@4.3.12 requires a peer of react@^15.0.0 || ^16.0.0 but none was installed.
npm WARN @reach/router@1.2.1 requires a peer of react@15.x || 16.x || 16.4.0-alpha.0911da3 but none was installed.
npm WARN @reach/router@1.2.1 requires a peer of react-dom@15.x || 16.x || 16.4.0-alpha.0911da3 but none was installed.
npm WARN create-react-context@0.2.3 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none was installed.
npm WARN react-helmet@5.2.0 requires a peer of react@>=15.0.0 but none was installed.
npm WARN react-side-effect@1.1.5 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0 but none was installed.

do we have to install everything one by one? Is there a quick way to solve this?

Thanks for help.

**Comment by mccrodp** [comment] 2018-11-30 06:02
The problem is that I defined the project using none specific versioning 🤦‍♂️ I will be looking at this soon to upgrade to Gatsby v2, but in the meantime, you can try to use the following versions in package.json and try again:

````
babel-plugin-styled-components@>1.5.0
├── dotenv@5.0.1
├── gatsby@1.9.250
├── gatsby-cli@1.1.46
├── gatsby-image@1.0.42
├── gatsby-link@1.6.40
├── gatsby-module-loader@1.0.11
├── gatsby-plugin-google-analytics@1.0.29
├── gatsby-plugin-i18n@0.4.1
├── gatsby-plugin-offline@1.0.15
├── gatsby-plugin-react-helmet@1.0.8
├── gatsby-plugin-sharp@1.6.43
├── gatsby-plugin-styled-components@2.0.11
├── gatsby-source-contentful@1.3.46
├── gatsby-transformer-remark@1.7.40
├── gatsby-transformer-sharp@1.6.23
├── intl@1.2.5
├── lodash@4.17.5
├── react-helmet@5.2.0
├── react-intl@2.4.0
├── react-typography@0.15.10
├── slash@1.0.0
├── styled-components@2.4.0
├── typography@0.15.12
└── typography-breakpoint-constants@0.14.0
````

**Comment by mccrodp** [comment] 2019-01-04 13:23
Hey @ergunpp , just upgraded to Gatsby v2, so closing this! 😄

**Closed as completed by mccrodp** 2019-01-04 13:23 UTC
